/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logica.main;
import java.io.File;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SSDesth
 */
public class FrmClienteVentanaUsuario extends javax.swing.JFrame {

    List<String> listaComandosCammp = new ArrayList();

    /**
     * Creates new form FrmClienteVentanaUsuario
     */
    public FrmClienteVentanaUsuario() {
        initComponents();
        CargarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombreBase = new javax.swing.JTextField();
        btnAgregarBase = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombreTabla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfNombreCampo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbTipoDato = new javax.swing.JComboBox<>();
        jcbObligatorio = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jcbTablaBaseDestino = new javax.swing.JComboBox<>();
        btnAgregarCampo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCamposTabla = new javax.swing.JTextArea();
        btnAgregarTabla = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbBaseEliminar = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcbEliminarTabla = new javax.swing.JComboBox<>();
        btnEliminarTabla = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbBaseCabiarNombre = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jcbTablaCambiarNombre = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jtfCambiarNombreNombre = new javax.swing.JTextField();
        btnCambiarNombre = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jcbTablaRegistroManual = new javax.swing.JComboBox<>();
        jcbBaseRegistroManual = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaEstructura = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jtfDatosRegistroManual = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnAgregarManualRegistro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jcbBaseArchivo = new javax.swing.JComboBox<>();
        jcbTablaArchivo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(226, 226, 226));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Base de Datos");

        jLabel2.setText("Nombre de La Base:");

        btnAgregarBase.setText("Agregar BAse de Datos");
        btnAgregarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNombreBase)
                    .addComponent(btnAgregarBase, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtfNombreBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarBase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(226, 226, 226));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crear Tabla");

        jLabel4.setText("Nombre de la Tabla");

        jLabel5.setText("Estructura de la Tabla:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Tipo Dato:");

        jcbTipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbObligatorio.setText("Requerido");

        jLabel8.setText("Base de Datos:");

        jcbTablaBaseDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarCampo.setText("Agregar Campo");
        btnAgregarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCampoActionPerformed(evt);
            }
        });

        jtaCamposTabla.setEditable(false);
        jtaCamposTabla.setColumns(20);
        jtaCamposTabla.setRows(5);
        jScrollPane1.setViewportView(jtaCamposTabla);

        btnAgregarTabla.setText("Agregar Tabla");
        btnAgregarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtfNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTablaBaseDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbObligatorio)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtfNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTablaBaseDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbObligatorio)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAgregarCampo)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarTabla)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(226, 226, 226));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Eliminar Tabla");

        jLabel10.setText("Base:");

        jcbBaseEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBaseEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBaseEliminarActionPerformed(evt);
            }
        });

        jLabel11.setText("Tabla:");

        jcbEliminarTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEliminarTabla.setText("Eliminar Base");
        btnEliminarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jcbBaseEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jcbEliminarTabla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcbBaseEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcbEliminarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarTabla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CrearBase/CrearTabla/EliminarTabla", jPanel1);

        jPanel6.setBackground(new java.awt.Color(226, 226, 226));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cambiar Nombre");

        jLabel13.setText("Base:");

        jcbBaseCabiarNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBaseCabiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBaseCabiarNombreActionPerformed(evt);
            }
        });

        jLabel14.setText("Tabla:");

        jcbTablaCambiarNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Nuevo Nombre:");

        btnCambiarNombre.setText("Cambiar Nombre");
        btnCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jcbBaseCabiarNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCambiarNombreNombre))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTablaCambiarNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jcbBaseCabiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcbTablaCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfCambiarNombreNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCambiarNombre)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(226, 226, 226));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Insertar Registro Manualmente");

        jLabel17.setText("Tabla:");

        jcbTablaRegistroManual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTablaRegistroManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTablaRegistroManualActionPerformed(evt);
            }
        });

        jcbBaseRegistroManual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBaseRegistroManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBaseRegistroManualActionPerformed(evt);
            }
        });

        jLabel18.setText("Base:");

        jtaEstructura.setEditable(false);
        jtaEstructura.setColumns(20);
        jtaEstructura.setRows(5);
        jScrollPane2.setViewportView(jtaEstructura);

        jLabel19.setText("Datos A Ingresar:");

        jLabel20.setBackground(new java.awt.Color(120, 139, 244));
        jLabel20.setForeground(new java.awt.Color(80, 109, 231));
        jLabel20.setText("int:1 - String:'Texto' - boolean:true/flase - float: 2.0");

        btnAgregarManualRegistro.setText("Agregar Registro");
        btnAgregarManualRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarManualRegistroActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel20))
                                .addComponent(jtfDatosRegistroManual))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnAgregarManualRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbBaseRegistroManual, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(33, 33, 33)
                        .addComponent(jcbTablaRegistroManual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jcbTablaRegistroManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBaseRegistroManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDatosRegistroManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarManualRegistro)
                    .addComponent(jButton2))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(226, 226, 226));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Insertar Registro Archivo");

        jLabel22.setText("Base:");

        jcbBaseArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBaseArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBaseArchivoActionPerformed(evt);
            }
        });

        jcbTablaArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setText("Tabla:");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jcbBaseArchivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTablaArchivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jcbBaseArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jcbTablaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("CambiarNombre/Mantenimiento de datos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBaseActionPerformed
        if (!jtfNombreBase.getText().equals("")) {

            if (main.miControlador.AgregarDatabase(jtfNombreBase.getText())) {
                JOptionPane.showMessageDialog(this, "Base de datos creada exitosamente");
                jtfNombreBase.setText("");
                CargarBases();

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo Crear la base de datos", "Alerta", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se puede crear una \n"
                    + "Base de datos sin nombre", "Alerta", 2);
        }

    }//GEN-LAST:event_btnAgregarBaseActionPerformed

    private void btnAgregarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCampoActionPerformed
        String Campo = "";
        if (ValidarAgregarCampoTabla()) {
            Campo = CrearComandoCampo();
            jtaCamposTabla.setText(jtaCamposTabla.getText() + Campo + "\n");
            listaComandosCammp.add(Campo);
            jtfNombreCampo.setText("");
            jcbObligatorio.setSelected(false);

        }


    }//GEN-LAST:event_btnAgregarCampoActionPerformed

    private void btnAgregarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTablaActionPerformed
        String comando = "";
        if (ValidarAgregarTabla()) {
            comando = CrearComandoTabla();

            System.out.println(comando);
            if (main.miControlador.AgregarTabla(jcbTablaBaseDestino.getItemAt(
                    jcbTablaBaseDestino.getSelectedIndex()), comando)) {
                JOptionPane.showMessageDialog(this, "tabla agregada exitosamente");
                listaComandosCammp = new ArrayList();
                jtfNombreTabla.setText("");
                CargarBases();
            }
        }


    }//GEN-LAST:event_btnAgregarTablaActionPerformed

    private void jcbBaseEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBaseEliminarActionPerformed
        if (jcbBaseEliminar.getItemCount() > 0) {
            CargarEliminarTablas();
            System.out.println("Wereck");
        }
    }//GEN-LAST:event_jcbBaseEliminarActionPerformed

    private void btnEliminarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTablaActionPerformed

        String base = jcbBaseEliminar.getItemAt(jcbBaseEliminar.getSelectedIndex());
        String tabla = jcbEliminarTabla.getItemAt(jcbEliminarTabla.getSelectedIndex());
        System.out.println("Aqui:" + tabla + "a");
        if (!tabla.equals("")) {
            main.miControlador.EliminarTabla(base, tabla);
            CargarEliminarTablas();
        } else {
            JOptionPane.showMessageDialog(this, "No se puede eliminar una tabla si no existe",
                    "Alerta", 2);
        }

    }//GEN-LAST:event_btnEliminarTablaActionPerformed

    private void btnCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNombreActionPerformed
        String base=jcbBaseCabiarNombre.getItemAt(jcbBaseCabiarNombre.getSelectedIndex());
        String tabla=jcbTablaCambiarNombre.getItemAt(jcbTablaCambiarNombre.getSelectedIndex());
        String nuevoNombre= jtfCambiarNombreNombre.getText();
        if(ValidarCambiarNombre(base, tabla, nuevoNombre)){
            if(main.miControlador.CambiarNombreTabla(base, tabla, nuevoNombre)){
                JOptionPane.showMessageDialog(this, "Se pudo cambiar el nombre de la tabla");
                CargarBases();
            }
            else{
                JOptionPane.showMessageDialog(this,"No se pudo cambiar el nombre de la tabla", "Alerta", 2);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Faltan datos para cambiar nombre", "Alerta", 2);
        }
        
    }//GEN-LAST:event_btnCambiarNombreActionPerformed

    private void jcbBaseCabiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBaseCabiarNombreActionPerformed
         if (jcbBaseEliminar.getItemCount() > 0) {
            CargarCambiarNombreTablas();
            System.out.println("Wereck");
        }
        
        
    }//GEN-LAST:event_jcbBaseCabiarNombreActionPerformed

    private void jcbBaseRegistroManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBaseRegistroManualActionPerformed
        if (jcbBaseRegistroManual.getItemCount() > 0) {
            CargarRegistromanualTablas();
        }
        
    }//GEN-LAST:event_jcbBaseRegistroManualActionPerformed

    private void jcbTablaRegistroManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTablaRegistroManualActionPerformed
       String Base= jcbBaseRegistroManual.getItemAt(jcbBaseRegistroManual.getSelectedIndex());
       String tabla = jcbTablaRegistroManual.getItemAt(jcbTablaRegistroManual.getSelectedIndex());
        System.out.println("sas"+tabla);
       if(tabla!= null){
        jtaEstructura.setText(main.miControlador.MostrarEstructura(Base, tabla));
       }
    }//GEN-LAST:event_jcbTablaRegistroManualActionPerformed

    private void btnAgregarManualRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarManualRegistroActionPerformed
        String temporal=jtfDatosRegistroManual.getText();
        String Base= jcbBaseRegistroManual.getItemAt(jcbBaseRegistroManual.getSelectedIndex());
        String tabla = jcbTablaRegistroManual.getItemAt(jcbTablaRegistroManual.getSelectedIndex());
       
        if(!temporal.equals("")){
            String comando = "("+temporal+")";
            main.miControlador.AgregarInformacionTabla(Base, tabla, comando);
        }
        
        
        
        
    }//GEN-LAST:event_btnAgregarManualRegistroActionPerformed

    private void jcbBaseArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBaseArchivoActionPerformed
        if (jcbBaseArchivo.getItemCount() > 0) {
            CargarRegistroArchivolTablas();
            
            
        }
    }//GEN-LAST:event_jcbBaseArchivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*JFileChooser temp = new JFileChooser();
        temp.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File archivo =temp.getSelectedFile();*/
        // System.out.println(archivo.toPath());
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClienteVentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClienteVentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClienteVentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClienteVentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClienteVentanaUsuario().setVisible(true);
            }
        });
    }

    public void CargarVentana() {
        jcbTipoDato.removeAllItems();
        jcbTipoDato.addItem("Int");
        jcbTipoDato.addItem("String");
        jcbTipoDato.addItem("Logico");
        jcbTipoDato.addItem("Float");

        CargarBases();

    }

    public boolean ValidarAgregarTabla() {
        if (jtfNombreTabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre de la tabla\n"
                    + " Es Obligatorio de ser rellenado", "Alerta", 2);
            return false;
        }
        if (listaComandosCammp.size() < 2) {
            JOptionPane.showMessageDialog(this, "Los Campos de la tabla\n"
                    + "Deben contar con un minimo de 2", "Alerta", 2);
            return false;
        }

        return true;
    }

    public boolean ValidarAgregarCampoTabla() {

        if (jtfNombreCampo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre del campo\n"
                    + " Es Obligatorio de ser rellenado", "Alerta", 2);
            return false;
        }
        for (String temp : listaComandosCammp) {
            String[] aux = temp.split(" ");
            if (aux[0].equals(jtfNombreCampo.getText())) {
                JOptionPane.showMessageDialog(this, "El nombre del campo\n"
                        + " No puede estar repetido", "Alerta", 2);
                return false;
            }
        }
        return true;
    }

    public String CrearComandoCampo() {
        String salida = "";
        salida += jtfNombreCampo.getText() + " ";
        switch (jcbTipoDato.getItemAt(jcbTipoDato.getSelectedIndex())) {
            case "Int":
                salida += "int";
                break;
            case "String":
                salida += "varchar(255)";
                break;
            case "Logico":
                salida += "boolean";
                break;
            case "Float":
                salida += "FLOAT(8,4)";
                break;
        }

        if (jcbObligatorio.isSelected()) {
            salida += " NOT NULL";
        }

        System.out.println(salida);
        return salida;
    }

    public String CrearComandoTabla() {
        String salida = "";
        salida += jtfNombreTabla.getText() + " (";

        for (int i = 0; i < listaComandosCammp.size(); i++) {
            salida += listaComandosCammp.get(i);
            if (i != (listaComandosCammp.size() - 1)) {
                salida += ", ";
            }
        }
        salida += ");";
        return salida;
    }

    public void CargarBases() {
        List<String> temp = main.miControlador.MostrarBases();
        jcbTablaBaseDestino.removeAllItems();
        jcbBaseEliminar.removeAllItems();
        jcbBaseCabiarNombre.removeAllItems();
        jcbBaseRegistroManual.removeAllItems();
        jcbBaseArchivo.removeAllItems();
        
        for (String aux : temp) {
            jcbTablaBaseDestino.addItem(aux);
            jcbBaseEliminar.addItem(aux);
            jcbBaseCabiarNombre.addItem(aux);
            jcbBaseRegistroManual.addItem(aux);
            jcbBaseArchivo.addItem(aux);
        }

    }

    public void CargarEliminarTablas() {
        String base = jcbBaseEliminar.getItemAt(jcbBaseEliminar.getSelectedIndex());

        jcbEliminarTabla.removeAllItems();

        List<String> tablas = main.miControlador.MostrarTablas(base);

        for (String temp : tablas) {
            jcbEliminarTabla.addItem(temp);
        }
    }

    public void CargarCambiarNombreTablas() {

        String base = jcbBaseCabiarNombre.getItemAt(jcbBaseCabiarNombre.getSelectedIndex());

        jcbTablaCambiarNombre.removeAllItems();

        List<String> tablas = main.miControlador.MostrarTablas(base);

        for (String temp : tablas) {
            jcbTablaCambiarNombre.addItem(temp);
        }
        
    }

    public void CargarRegistromanualTablas() {

        String base = jcbBaseRegistroManual.getItemAt(jcbBaseRegistroManual.getSelectedIndex());

        jcbTablaRegistroManual.removeAllItems();

        List<String> tablas = main.miControlador.MostrarTablas(base);

        for (String temp : tablas) {
            jcbTablaRegistroManual.addItem(temp);
        }
        
    }

    public void CargarRegistroArchivolTablas() {

        String base = jcbBaseArchivo.getItemAt(jcbBaseArchivo.getSelectedIndex());

        jcbTablaArchivo.removeAllItems();

        List<String> tablas = main.miControlador.MostrarTablas(base);

        for (String temp : tablas) {
            jcbTablaArchivo.addItem(temp);
        }
        
    }
    
    public boolean ValidarCambiarNombre(String base,String nombre, String nuevoNombre){
        if(base.equals("")||nombre.equals("")||nuevoNombre.equals("")){
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarBase;
    private javax.swing.JButton btnAgregarCampo;
    private javax.swing.JButton btnAgregarManualRegistro;
    private javax.swing.JButton btnAgregarTabla;
    private javax.swing.JButton btnCambiarNombre;
    private javax.swing.JButton btnEliminarTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbBaseArchivo;
    private javax.swing.JComboBox<String> jcbBaseCabiarNombre;
    private javax.swing.JComboBox<String> jcbBaseEliminar;
    private javax.swing.JComboBox<String> jcbBaseRegistroManual;
    private javax.swing.JComboBox<String> jcbEliminarTabla;
    private javax.swing.JCheckBox jcbObligatorio;
    private javax.swing.JComboBox<String> jcbTablaArchivo;
    private javax.swing.JComboBox<String> jcbTablaBaseDestino;
    private javax.swing.JComboBox<String> jcbTablaCambiarNombre;
    private javax.swing.JComboBox<String> jcbTablaRegistroManual;
    private javax.swing.JComboBox<String> jcbTipoDato;
    private javax.swing.JTextArea jtaCamposTabla;
    private javax.swing.JTextArea jtaEstructura;
    private javax.swing.JTextField jtfCambiarNombreNombre;
    private javax.swing.JTextField jtfDatosRegistroManual;
    private javax.swing.JTextField jtfNombreBase;
    private javax.swing.JTextField jtfNombreCampo;
    private javax.swing.JTextField jtfNombreTabla;
    // End of variables declaration//GEN-END:variables
}
